### ISSUE TITLE
What's the advantages compared with np?

### ISSUE THREAD

**Issue by nanokind** [int64ago/peta#2]
https://github.com/sindresorhus/np

```bash
$ np prerelease --tag=beta
```

... :sweat_smile:

**Comment by int64ago** [comment]
`peta` is for publishing with **automatically** increased  version number, and it's **ONLY** for beta tag publishing.

Actually, it's written for [nek-ui](https://github.com/kaola-fed/nek-ui) workflow...

**Comment by nanokind** [comment]
刚好进你主页看到了这个项目，其实我只是来安利np的，挺好用的 :joy:

**Comment by int64ago** [comment]
@fengzilong 所以我看到立马 star 了……我还知道个 [xyz](https://github.com/davidchambers/xyz) 做类似的事，不过跟 np 比还是太简陋了……
